
package com.iftm.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExemploService", targetNamespace = "http://iftm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExemploService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcula", targetNamespace = "http://iftm.com/", className = "com.iftm.cliente.Calcula")
    @ResponseWrapper(localName = "calculaResponse", targetNamespace = "http://iftm.com/", className = "com.iftm.cliente.CalculaResponse")
    @Action(input = "http://iftm.com/ExemploService/calculaRequest", output = "http://iftm.com/ExemploService/calculaResponse")
    public int calcula(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nome", targetNamespace = "http://iftm.com/", className = "com.iftm.cliente.Nome")
    @ResponseWrapper(localName = "nomeResponse", targetNamespace = "http://iftm.com/", className = "com.iftm.cliente.NomeResponse")
    @Action(input = "http://iftm.com/ExemploService/nomeRequest", output = "http://iftm.com/ExemploService/nomeResponse")
    public String nome();

}
